version: '3'
  
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  narrow:
    build: ./Narrow
    command: sh run.sh
    volumes:
      - .:/Narrow
    ports:
      - "8000:8000"
    depends_on:
      - db
